# Generated by Django 3.0.4 on 2020-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200427_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pass_word',
            field=models.IntegerField(default=6792),
        ),
    ]
