# Generated by Django 3.0.4 on 2020-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_pass_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='pass_word',
            field=models.IntegerField(default=7139),
        ),
    ]
